pimcore:
    assets:
        image:
            thumbnails:
                definitions:
                    hero:
                        items:
                            -
                                method: cover
                                arguments:
                                    width: 1980
                                    height: 1080
                                    positioning: center
                                    forceResize: false
                        medias: {  }
                        name: square
                        description: ''
                        group: ''
                        format: SOURCE
                        quality: 85
                        highResolution: null
                        preserveColor: false
                        preserveMetaData: false
                        rasterizeSVG: false
                        downloadable: false
                        modificationDate: 1741244860
                        creationDate: 1741244851
                        preserveAnimation: false
