pimcore:
    assets:
        image:
            thumbnails:
                definitions:
                    product:
                        items:
                            -
                                method: scaleByWidth
                                arguments:
                                    width: 500
                                    forceResize: false
                            -
                                method: setBackgroundColor
                                arguments:
                                    color: '#fff'
                        medias: {  }
                        name: product
                        description: ''
                        group: ''
                        format: SOURCE
                        quality: 85
                        highResolution: null
                        preserveColor: false
                        preserveMetaData: false
                        rasterizeSVG: false
                        downloadable: false
                        modificationDate: 1741264026
                        creationDate: 1741264005
                        preserveAnimation: false
