pimcore_admin:
    branding:
        login_screen_invert_colors: false
        color_login_screen: '#dc211c'
        color_admin_interface: '#dc211c'
        color_admin_interface_background: ''
        login_screen_custom_image: 'https://ager.ager.farm/Unternehmen/ager-speck-soell.jpg'
    assets:
        hide_edit_image: false
        disable_tree_preview: true
